// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.3
// source: getter.proto

package pb_test_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetName) Reset() {
	*x = GetName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetName) ProtoMessage() {}

func (x *GetName) ProtoReflect() protoreflect.Message {
	mi := &file_getter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetName.ProtoReflect.Descriptor instead.
func (*GetName) Descriptor() ([]byte, []int) {
	return file_getter_proto_rawDescGZIP(), []int{0}
}

type GetName_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetName_Request) Reset() {
	*x = GetName_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetName_Request) ProtoMessage() {}

func (x *GetName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_getter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetName_Request.ProtoReflect.Descriptor instead.
func (*GetName_Request) Descriptor() ([]byte, []int) {
	return file_getter_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetName_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetName_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetName_Response) Reset() {
	*x = GetName_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetName_Response) ProtoMessage() {}

func (x *GetName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_getter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetName_Response.ProtoReflect.Descriptor instead.
func (*GetName_Response) Descriptor() ([]byte, []int) {
	return file_getter_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_getter_proto protoreflect.FileDescriptor

var file_getter_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x65, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x70, 0x62, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x48, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x32, 0x4e, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x44,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x3b,
	0x70, 0x62, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_getter_proto_rawDescOnce sync.Once
	file_getter_proto_rawDescData = file_getter_proto_rawDesc
)

func file_getter_proto_rawDescGZIP() []byte {
	file_getter_proto_rawDescOnce.Do(func() {
		file_getter_proto_rawDescData = protoimpl.X.CompressGZIP(file_getter_proto_rawDescData)
	})
	return file_getter_proto_rawDescData
}

var file_getter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_getter_proto_goTypes = []interface{}{
	(*GetName)(nil),          // 0: pb.test.v1.GetName
	(*GetName_Request)(nil),  // 1: pb.test.v1.GetName.Request
	(*GetName_Response)(nil), // 2: pb.test.v1.GetName.Response
}
var file_getter_proto_depIdxs = []int32{
	1, // 0: pb.test.v1.Getter.GetName:input_type -> pb.test.v1.GetName.Request
	2, // 1: pb.test.v1.Getter.GetName:output_type -> pb.test.v1.GetName.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getter_proto_init() }
func file_getter_proto_init() {
	if File_getter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetName_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetName_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getter_proto_goTypes,
		DependencyIndexes: file_getter_proto_depIdxs,
		MessageInfos:      file_getter_proto_msgTypes,
	}.Build()
	File_getter_proto = out.File
	file_getter_proto_rawDesc = nil
	file_getter_proto_goTypes = nil
	file_getter_proto_depIdxs = nil
}
